### PR TITLE
fix: execve allow NULL argv and envp

### LINKED ISSUE #17: posix_spawnp related execve bad address bug
**Description**
The `posix_spawnp` function, when called by `musl` libc, fails to create a new process. This is due to two distinct issues in the StarryOS kernel:
- The `execve` syscall returns `EFAULT` (Bad address) when attempting to load the new program image.

**Location**:
*   `starry_api::syscall::task::execve` (for the `EFAULT` error)

**Environment**
*   **Architecture**: `aarch64` (ARM64)
*   **Platform**: `QEMU virt`

**Test Code**
The issue is reproducible using the `libc-test` suite's `src/functional/spawn.c` test, which can be found here: https://github.com/AssemblyScript/libc-test/blob/master/src/functional/spawn.c

Cross-compiling using aarch64-linux-musl-gcc, loading compiled test executable files into root directory of StarryOS, and lastly, executing the test. The entire compiling and testing process can be found here in Simplified Chinese: https://haozewu.notion.site/StarryOS-musl-libc-test-29b2127bdf2e80698d9de10d6fb2d3c8

Relevant failing lines from `src/functional/spawn.c`:
```c
// This line fails with "got 14 want 0" (EFAULT)
TEST(posix_spawnp(&pid, "echo", &fa, 0, (char *[]){"echo","hello",0}, 0), 0);
```

**Kernel Log / Debug Output**
```
// From the initial posix_spawnp call's child process (Task 12):
[ 13.241957 0:12 starry_api::syscall:606] Syscall execve return Err(BadAddress)
```

The entire debug -level output can is given here: https://haozewu.notion.site/posix_spawnp-log-29b2127bdf2e80f8b346c5df65616ac0

**Root Cause**

**`execve` returns `Err(BadAddress)`:**
    *   **Problem:** The `execve` syscall in StarryOS may be incorrectly validating or handling user-provided pointers for the program path, `argv` (arguments), or `envp` (environment variables). When `musl`'s `child` function calls `execve`, the kernel determines that one of these pointers (or the data they point to) is invalid, returning `EFAULT`.

However, simply running `execve` with params `{"echo", "hello", NULL}` won't be an issue, the `execve` syscall can be handled perfectly by Starry OS in this case.

### PR DESCRIPTION
**Pull request by Blankke**
This PR is mean to solve issue #17 
The configuration process followed the original issue description, keeping only the spawn test.
- First, I located the implementation of the execve system call in StarryOS: execve.rs.
```c
TEST(posix_spawnp(&pid, "echo", &fa, 0, (char *[]){"echo","hello",0}, 0);
```
- The code above is from the libc test. Here, the environment variable parameter for spawn (which ultimately calls execve) is passed as 0.

- According to the POSIX standard, execve allows envp to be NULL (indicating an empty environment).
-  However, StarryOS's implementation did not handle this case and directly called vm_load_until_nul on the NULL pointer, resulting in an EFAULT (Bad Address) error.

- I checked the Linux execve implementation in QEMU and found that it checks if the pointer is NULL before processing envp.

- I added checks for both arg and env:
```rust
    // Handle NULL argv (treat as empty array)
    let args = if argv.is_null() {
        Vec::new()
    } else {
        vm_load_until_nul(argv)?
            .into_iter()
            .map(vm_load_string)
            .collect::<Result<Vec<_>, _>>()?
    };

    // Handle NULL envp (treat as empty array)
    let envs = if envp.is_null() {
        Vec::new()
    } else {
        vm_load_until_nul(envp)?
            .into_iter()
            .map(vm_load_string)
            .collect::<Result<Vec<_>, _>>()?
    };
```

tests are proved to get passed

### CODE REVIEW

File: api/src/syscall/task/execve.rs [hunk 1]
```diff
@@ -18,15 +18,25 @@ pub fn sys_execve(
 ) -> AxResult<isize> {
     let path = vm_load_string(path)?;
 
-    let args = vm_load_until_nul(argv)?
-        .into_iter()
-        .map(vm_load_string)
-        .collect::<Result<Vec<_>, _>>()?;
+    // Handle NULL argv (treat as empty array)
+    let args = if argv.is_null() {
+        Vec::new()
```
Comment (AsakuraMizu) [inline api/src/syscall/task/execve.rs]:
```suggestion
    let args = if argv.is_null() {
        // Handle NULL argv (treat as empty array)
        Vec::new()
```

File: api/src/syscall/task/execve.rs [hunk 2]
```diff
@@ -18,15 +18,25 @@ pub fn sys_execve(
...
+            .into_iter()
+            .map(vm_load_string)
+            .collect::<Result<Vec<_>, _>>()?
+    };
 
-    let envs = vm_load_until_nul(envp)?
-        .into_iter()
-        .map(vm_load_string)
-        .collect::<Result<Vec<_>, _>>()?;
+    // Handle NULL envp (treat as empty array)
```
Comment (AsakuraMizu) [inline api/src/syscall/task/execve.rs]: Same here.

**Review by AsakuraMizu — CHANGES_REQUESTED** [review]

File: api/src/syscall/task/execve.rs (hunk 2 above)
Comment (Blankke) [reply api/src/syscall/task/execve.rs]: Sorry, I've missed. 
I just did the minimum modification for pass the test.
Thx
