### PR TITLE
fix: implement signalfd

### LINKED ISSUE #15: signalfd4 syscall crashes with `unimplemented!()` panic
## Description

The `signalfd4` syscall returns a broken file descriptor that crashes when attempting to read from it.

**Severity**: CRITICAL - Causes system panic
**Location**: `api/src/syscall/fs/io.rs:25`

## Environment

- **Architecture**: aarch64 (ARM64)
- **Platform**: QEMU virt

## Test Code

```rust
// signalfd_test/src/main.rs
fn test_create_signalfd() -> io::Result<RawFd> {
    unsafe {
        // Create signal mask for SIGUSR1 and SIGUSR2
        let mut sigmask: libc::sigset_t = std::mem::zeroed();
        libc::sigemptyset(&mut sigmask);
        libc::sigaddset(&mut sigmask, libc::SIGUSR1);
        libc::sigaddset(&mut sigmask, libc::SIGUSR2);

        // Create signalfd
        let fd = libc::syscall(
            libc::SYS_signalfd4,           // syscall number (74 on aarch64)
            -1i32,                          // fd (-1 to create new)
            &sigmask as *const _,           // signal mask
            std::mem::size_of::<libc::sigset_t>(),
            libc::SFD_CLOEXEC,             // flags
        ) as RawFd;

        // Returns valid fd (e.g., 3)
        Ok(fd)
    }
}

fn test_read_signalfd(fd: RawFd) -> io::Result<()> {
    unsafe {
        let mut file = File::from_raw_fd(fd);
        let mut buffer = [0u8; 128];  // signalfd_siginfo is 128 bytes

        // THIS CRASHES:
        match file.read(&mut buffer) {
            Ok(n) => println!("Read {} bytes", n),
            Err(e) => eprintln!("Error: {}", e),
        }

        std::mem::forget(file);
    }
    Ok(())
}
```

## Crash Backtrace

```
Backtrace:
   0: __rustc::rust_begin_unwind
            at arceos/modules/axruntime/src/lang_items.rs:6:23
   1: core::panicking::panic_fmt
            at /rustc/60dabef95a3de3ec974dcb50926e4bfe743f078f/library/core/src/panicking.rs:75:14
   2: core::panicking::panic
            at /rustc/60dabef95a3de3ec974dcb50926e4bfe743f078f/library/core/src/panicking.rs:145:5
   3: <starry_api::syscall::fs::io::DummyFd as starry_api::file::FileLike>::read
            at api/src/syscall/fs/io.rs:25:9
   4: starry_api::syscall::fs::io::sys_read
            at api/src/syscall/fs/io.rs:67:8
   5: starry_api::syscall::handle_syscall
            at api/src/syscall/mod.rs:137:24
```

## Root Cause

**File**: `api/src/syscall/fs/io.rs:22-43`

```rust
struct DummyFd;
impl FileLike for DummyFd {
    fn read(&self, _dst: &mut SealedBufMut) -> AxResult<usize> {
        unimplemented!()  // ← CRASHES HERE (line 25)
    }

    fn write(&self, _src: &mut SealedBuf) -> AxResult<usize> {
        unimplemented!()
    }

    fn stat(&self) -> AxResult<crate::file::Kstat> {
        unimplemented!()
    }

    fn path(&self) -> Cow<str> {
        "anon_inode:[bruh]".into()
    }
    // ...
}
```

The syscall returns a valid file descriptor, but it's backed by `DummyFd` which has `unimplemented!()` in all I/O methods.

### PR DESCRIPTION
**Pull request by yoinspiration**
- Add Signalfd file descriptor implementation (api/src/file/signalfd.rs)
- Implement signalfd4 system call handler (api/src/syscall/fs/signalfd.rs)
- Register signalfd4 in syscall router (api/src/syscall/mod.rs)
- Export signalfd module in file/mod.rs and syscall/fs/mod.rs

This fixes the panic when reading from signalfd4 file descriptor. Previously, signalfd4 returned a DummyFd which would panic on read. Now it returns a proper Signalfd that can read signals correctly.

Fixes #15

### CODE REVIEW

**Comment by AsakuraMizu** [comment]
Please refer to https://docs.github.com/zh/get-started/git-basics/configuring-git-to-handle-line-endings and update your commit. I can not identify your changes in diff.

**Comment by yoinspiration** [comment]
I've updated the commit according to the GitHub documentation on configuring Git to handle line endings.

## What I've Done

1. Added `.gitattributes` file to ensure consistent line endings (LF)
2. Reorganized the commit to clearly show only the actual code changes

## Result

The commit now displays clean, readable diffs:
- **6 files changed, 300 insertions(+), 3 deletions(-)**
- New files: `api/src/file/signalfd.rs` (194 lines) and `api/src/syscall/fs/signalfd.rs` (65 lines)
- Modified files show only relevant changes (e.g., `api/src/file/mod.rs` shows just 1 line: `+pub mod signalfd;`)

The diff statistics are consistent with or without whitespace ignored, confirming the line ending issue is resolved. You should now be able to clearly identify all code changes in the diff.

**Comment by yoinspiration** [comment]
Thank you for the thorough review! I've addressed all the comments:

1. **SFD flag constants**: Updated to use `O_CLOEXEC` and `O_NONBLOCK` from `linux_raw_sys::general` instead of hardcoded values, following the same pattern as `pipe.rs` and `event.rs`.

2. **Chinese comments**: Translated all Chinese comments to English for consistency with the codebase.

3. **Unsafe block formatting**: Removed the empty line and updated the comment to use singular "field" since only one field is accessed.

All changes have been committed and pushed. The implementation now correctly handles the signalfd4 flags and maintains consistency with the rest of the codebase.

**Comment by yoinspiration** [comment]
Thanks for the additional feedback! I've addressed each comment in the latest commit:
- Updated `SignalfdSiginfo` to avoid packed-struct UB and added helper for the union access.
- `Signalfd` now allows mask updates when `fd != -1`, matching the Linux spec.
- Byte serialization uses `ptr::addr_of!` to avoid unaligned references.

Please let me know if anything else needs adjustment!

File: api/src/file/signalfd.rs [hunk 1]
```diff
@@ -0,0 +1,198 @@
...
+    _pad: [u8; 46],      // Padding to make it 128 bytes
+}
+
+const _: [(); SIGNALFD_SIGINFO_SIZE] = [(); mem::size_of::<SignalfdSiginfo>()];
+
+fn siginfo_errno(sig_info: &SignalInfo) -> i32 {
+    // SAFETY: The union layout matches Linux's siginfo_t definition. bindgen keeps this layout,
+    // so it is safe to read the errno field through the anonymous union.
+    unsafe { sig_info.0.__bindgen_anon_1.__bindgen_anon_1.si_errno }
+}
```
Comment (AsakuraMizu) [inline api/src/file/signalfd.rs]: Add this function as `SignalInfo::errno` into https://github.com/Starry-OS/starry-signal/blob/main/src/types.rs

**Review by AsakuraMizu — CHANGES_REQUESTED** [review]

File: api/src/file/signalfd.rs (hunk 1 above)
Comment (yoinspiration) [reply api/src/file/signalfd.rs]: Fixed in commit 578e473
The clippy warning has been resolved by changing self.mask.read().clone() to *self.mask.read() on line 98. Since SignalSet implements Copy, we can directly dereference instead of cloning.
Also refactored to use SignalInfo::errno() method instead of the standalone siginfo_errno function.

**Comment by yoinspiration** [comment]
need to accept this pull request https://github.com/Starry-OS/starry-signal/pull/5 first in starry-signal repository, or it will encounter CI errors without SignalInfo::errno() method

File: api/src/file/signalfd.rs [hunk 2]
```diff
@@ -0,0 +1,192 @@
...
+
+        Poller::new(self, IoEvents::IN)
+            .non_blocking(self.nonblocking())
+            .poll(|| {
+                if let Some(sig_info) = self.dequeue_signal() {
+                    // Convert SignalInfo to SignalfdSiginfo
+                    let sfd_info = SignalfdSiginfo::from_signal_info(&sig_info);
+                    
+                    // Write the structure to the destination buffer
+                    let bytes = unsafe {
```
Comment (AsakuraMizu) [inline api/src/file/signalfd.rs]: nit: use [bytemuck](https://docs.rs/bytemuck/) or [zerocopy](https://docs.rs/zerocopy) to safely transmute C structs to bytes.

Comment (yoinspiration) [reply api/src/file/signalfd.rs]: **Fixed** ✅

Replaced the unsafe transmute with `zerocopy::IntoBytes` for safe C struct-to-bytes conversion.

**Changes made:**

1. Added `use zerocopy::IntoBytes;` import (line 16)
2. Added `#[derive(IntoBytes)]` to the `SignalfdSiginfo` struct (line 26)
3. Replaced the unsafe code block with `sfd_info.as_bytes()` (line 134)

**Relevant code:**

```rust
// Line 26-27: Added IntoBytes derive
#[repr(C)]
#[derive(IntoBytes)]
struct SignalfdSiginfo {
    // ...
}
```

```rust
// Line 133-135: Replaced unsafe transmute with safe conversion
// Write the structure to the destination buffer
let bytes = sfd_info.as_bytes();
dst.write(bytes)?;
```

The code now safely converts the C struct to bytes using `zerocopy` without any unsafe blocks, which is consistent with the approach used in `api/src/vfs/dev/event.rs`.

**Review by AsakuraMizu — APPROVED** [review]

**Comment by AsakuraMizu** [comment]
You forgot to update `Cargo.lock` xd

**Comment by yoinspiration** [comment]
True, my bad — thanks for updating it!

**Comment by yoinspiration** [comment]
True, my bad ― thanks for updating it!
________________________________
发件人: 朝}水希 ***@***.***>
发送时间: 2025年11月20日 12:12
收件人: Starry-OS/StarryOS ***@***.***>
抄送: yoinspiration ***@***.***>; State change ***@***.***>
主题: Re: [Starry-OS/StarryOS] fix: implement signalfd (PR #31)

[https://avatars.githubusercontent.com/u/17076564?s=20&v=4]AsakuraMizu left a comment (Starry-OS/StarryOS#31)<https://github.com/Starry-OS/StarryOS/pull/31#issuecomment-3555681518>

You forgot to update Cargo.lock xd

―
